# Metadata
sonar.projectName=hellobot-bff
sonar.projectVersion=${project.version}

# Source information
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.javascript.exclusions=**/*spec.ts
sonar.coverage.exclusions=**/*.module.ts,**/main.ts,**/utils/**/*.ts,**/*config.ts,**/*spec.ts,**/*dto.ts,**/*schema.ts,**/*mock.ts

# Tests
sonar.tests=src,test
sonar.test.inclusions=**/*spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.binaries=dist

# Debug
sonar.verbose=true