name: AAP CI
run-name: 🔁 CI Check

on:
  workflow_dispatch:
  push:

# Permissions are fine-grained managed at Reusable Workflows/Jobs level
permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  workflows-enforcement:
    name: Workflows
    uses: adeo/github-aap/.github/workflows/reusable-global-enforcement.yaml@main
