name: AAP Cleanup
run-name: ♻️ Cleanup

on:
  delete:
  workflow_dispatch:

# Permissions are fine-grained managed at Reusable Workflows/Jobs level
permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  hellobot-bff-Cleanup:
    name: "hellobot-bff"
    uses: adeo/github-aap/.github/workflows/reusable-component-nodejs-container-cleanup.yaml@main
    with:
      configuration: .aap.rc/ci/config.yml
