name: AAP Build
run-name: 🛠️ Build · ${{ github.head_ref || github.ref_name }}

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

# Permissions are fine-grained managed at Reusable Workflows/Jobs level
permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  hellobot-bff-build:
    name: "hellobot-bff"
    uses: adeo/github-aap/.github/workflows/reusable-component-nodejs-container-build.yaml@main
    with:
      configuration: .aap.rc/ci/config.yml
